### ISSUE TITLE
[JEI NeoTech crash] entworld client crash molten bronze nei, ZapperGhandi

### ISSUE THREAD

**Issue by ZapperGhandi** [Claycorp/EntWorld#2]
##### What is the problem?

Minecraft client crashed (closed to windows) when I was clicking on molten bronze in NEI
##### Client, Server or Both?

Not sure, but it seems only client.
##### Crash Report or FML-client-latest.log LINKS ONLY!

http://pastebin.com/CpFRYeYb
##### Can it be reproduced? If yes, explain.

Tried to reproduce it and failed. Did not manage to crash again =(

**Comment by Claycorp** [comment]
Its a issue with NeoTech. NeoTech is inactive and won't be fixed. NeoTech isn't on the server currently and will be removed next pack update. You can freely remove NeoTech from the pack if you wish.
