### ISSUE TITLE
[OutOfMemoryError]Loading PineFresh Crash

### ISSUE THREAD

**Issue by RiverMage** [Claycorp/EntWorld#3]
What is the problem?
     mid way through loading Pinefresh, my client crashes.  can't reach the main menu.

Client, Server or Both?
     I believe it's client, 
##### Crash Report or FML-client-latest.log LINKS ONLY!

(Files can be found by clicking the ... button in the top right hand corner of curse and clicking open file. Crash reports are in the crash reports folder and FML-client-latest.log is in the Logs folder.)  
Please post them on a website like http://pastebin.com/ or https://gist.github.com/

Link to Log: https://gist.github.com/RiverMage/f2e828d52bd85a48489012ff0eee5827

Can it be reproduced? If yes, explain.
1. Step 1: click "Play"
2. Step 2: wait 2 minutes as it's loading...
3. Step 3: crash to desktop

**Comment by Claycorp** [comment]
- Go to the curse options. 
- Click minecraft. 
- Slide the RAM slider to 3GB or more. (RAM available will depend on total installed.) I recommend 4-6GB if you have that much.
- Start minecraft! It should work again :+1:
