### ISSUE TITLE
Bear Meat cannot be cooked in a Kiln or Brick Oven

### ISSUE THREAD

**Issue by Turbohand** [Claycorp/EntWorld#6]
##### What is the problem?

Bear meat is one of the only meats that requires a furnace. All other meats are cooked in the Kiln or Brick Oven.

##### Crash Report or latest.log LINKS ONLY! 
(Files can be found by clicking the ... button in the top right hand corner of curse and clicking "Open Folder". Crash reports are in the Crash-Reports folder and latest.log is in the Logs folder.)   
Please post them on a website like http://pastebin.com/ or https://gist.github.com/

##### Can it be reproduced? If yes, explain.
1. Step 1
2. Step 2... ETC

**Comment by Claycorp** [comment]
Fixed in Dev2. There shouldn't be any foods left in the furnace, they all were moved to the oven and campfire if applicable.
